//
// Texturen
//
	const string MENU_VERSION			= "";
	// Menu
	const string MENU_BACK_PIC 			= "menu_option.tga"; 		// outgame/ingame
	const string MENU_ITEM_BACK_PIC 	= "";						// Hintergrund für alle anwählbaren Menüpunkte
	const string MENU_CHOICE_BACK_PIC	= "menu_choice_back.tga";	// Hintergrund für Choicebox
	const string MENU_SLIDER_BACK_PIC	= "menu_slider_back.tga";	// Hintergrund für Slider
	const string MENU_SLIDER_POS_PIC	= "menu_slider_pos.tga";	// Textur für Positionsanzeige eines Sliders
	const string MENU_INPUT_BACK_PIC 	= "menu_option.tga";						// Hintergrund für Eingabefelder
	const string MENU_KBDINPUT_BACK_PIC = "";						// Hintergrund fürs Definieren der Controls
	const string MENU_SAVELOAD_BACK_PIC = "menu_saveload_back.tga"; // menu_kbd_back.tga";		// Hintergrund fürs Definieren der Controls
	// Log
	const string LOG_BACK_PIC			= "log_back.tga";			// Hintergrund für den Log-Screen
	const string LOG_VIEWER_BACK_PIC	= "log_paper.tga";			// Hintergrund des Log-Betrachters
	// StaticScreen
	const string STAT_BACK_PIC			= "status_back.tga";		// Hintergrund

//
// Fonts
//
	
	// Menu
	const string MENU_FONT_DEFAULT		= "font_old_15_white.tga";
	const string MENU_FONT_SMALL		= "FONT_10_MENU_NEW.tga";
	const string MENU_FONT_BRIGHT		= "FONT_10_BOOK_RED.tga";
	// Log
	const string LOG_FONT_DEFAULT		= "FONT_10_BOOK.tga";//"FONT_10_MENU_NEW.tga";
	const string LOG_FONT_VIEWER		= "FONT_10_MENU_NEW.tga";
	const string LOG_FONT_DATETIME		= "FONT_10_BOOK.tga";	
	//	const string LOG_FONT_VIEWER		= "FONT_10_BOOK.tga";
	//	const string LOG_FONT_DATETIME		= "FONT_10_BOOK_RED.tga";		
	// StaticScreen
	const string STAT_FONT_DEFAULT		= "FONT_10_BOOK.tga";//"font_old_10_white.tga";
	//BugFix
	const string STAT_FONT_NOPERCENT		= "FONT_OLD_10_NOPERCENT.tga";	
	
	const string STAT_FONT_TITLE		= "FONT_10_BOOK.tga";//"font_old_10_white.tga";
	
	const string MENU_FONT_VERSION		= "font_old_10_white.tga";
	


//
// Dimensions
//

	const int MENU_SLIDER_DX			= 2000;
	const int MENU_SLIDER_DY			= 600;
	const int MENU_SLIDER_YPLUS			= 0;
	
	const int MENU_CHOICE_DX			= 800;
	const int MENU_CHOICE_DY			= 350;	
	const int MENU_CHOICE_YPLUS			= 250;
	
	const int MENU_TITLE_Y				= 1200;
	const int MENU_START_Y				= 2400;
	const int MENU_BACK_Y				= 6500;	
	const int MENU_DY					= 650;
	
	const int MENU_INFO_X				= 300;
	const int MENU_INFO_Y				= 180;
	
const int MENU_OPT_X 		=  3900;
const int MENU_OPT_X2 		=  3900;

//
// Texts (muss in die Text.d)
//

	const string MENU_TEXT_NEEDS_APPLY		= "";
	const string MENU_TEXT_NEEDS_RESTART	= "Einige Einstellungen werden erst nach einem Neustart aktiv";
