
//---------------------------------------
// Function fired by Poison_trigger
// every 125ms
//---------------------------------------
var int MusicSys_Inited;
var string MusicSys_Theme;
var string MusicSys_OldTheme;
var string MusicSys_OldThemePrefix;
var int OrcDLL_LIB;
var int OrcDLL_PlayMusic; 
var int OrcDLL_Tidy; 
var int OrcDLL_SetVolume;//set global music volume level
var int MusicSys_TidyDelay;
func void MusicSystem_Init()
{
	if(MusicSys_Inited)
	{ return; };	

	OrcDLL_LIB = LoadLibrary("orcLib.dll");
	OrcDLL_PlayMusic      = GetProcAddress(OrcDLL_LIB, "_Z16OrcLib_PlayMusicPKcf");

	OrcDLL_Tidy      = GetProcAddress(OrcDLL_LIB, "_Z11OrcLib_Tidyv");
	OrcDLL_SetVolume = GetProcAddress(OrcDLL_LIB, "_Z21OrcLib_SetMusicVolumef");
	printdebug_s_i_s_i("MS: orcLib.dll inited: ",OrcDLL_LIB," ::(play) ",OrcDLL_PlayMusic);
	printdebug_s_i_s_i("MS: tidy: ",OrcDLL_Tidy," ::(setVolume) ",OrcDLL_SetVolume);
	MusicSys_Inited = TRUE;
};

func void MusicSys_ReInit()//Called at INIT(All) in startup.d
{
	MusicSys_Inited = false;
};



const int MS_Default = 0;//std->std
const int MS_ToFight = 1;//std->fgt
const int MS_FromFight = 2;//fgt->std

// file - like "OC_DAY_STD.ogg" -> path & stuff generated by dll
// volume - in IEEE 754 (or sth) floatpoint 32bit (theese one by sektenspinner)
func void MusicSystem_PlayMusic(var string file, var int volume)
{
	// Now all this stuff is handled by dll itself
	/*if(Hlp_StrCmp(file,MusicSys_OldTheme))
	{
		return; //Don't apply same music preset	
	};
	*/
	MusicSystem_Init();
	printdebug("MS:Init done..");
	CALL_IntParam(volume);
	CALL_cStringPtrParam (file);
	CALL__cdecl(OrcDLL_PlayMusic);
	printdebug("MS:Music Played..");
	// Gothic wasn't very happy when he have to grab this msg's
	//get returnec Const char...
	//var string msg; 
    //var zString zStr;
	//printdebug("MS: Returning value..");
	//MEM_AssignInst (zStr, STRINT_GetHelpStringAddress());
	//zStr.ptr = CALL_RetValAsPtr();
	//zStr.len = 280;
	//printdebug("MS: orcLib_PlayMusic()->returned:");
	//msg = MEMINT_HlpString;
	//printdebug_ss("MS: orcLib::msg: ",msg);
	
	MusicSys_TidyDelay = 1000;//??? ahh so thats the time after tidy should be fired fuck that anyways ;d
	
	MusicSys_OldTheme = file;
	
};
func void MusicSystem_Tidy()//stop faded out channel
{
	MusicSystem_Init();//but at all it will be inited only when MusicSys_Inited == false (and after init it is true)
	
	CALL__cdecl(OrcDLL_Tidy);
	
	//var string msg; 
    //var zString zStr;
	//printdebug("MS: Returning value..");
	//MEM_AssignInst (zStr, STRINT_GetHelpStringAddress());
	//zStr.ptr = CALL_RetValAsPtr();
	//zStr.len = 280;
	//printdebug("MS: orcLib_Tidy()->returned:");
	//msg = MEMINT_HlpString;
	//printdebug_ss("MS: orcLib::msg: ",msg);
	
};

func string MusicSystem_GetTheme()
{
	var string zonevobname; var int vob;
	
	vob = MEM_ReadInt(MUSIC_Zone_Address);
	printdebug_s_i("ZONEVOB.ptr:",vob);
	if(vob)
	{
		zonevobname = MEM_ReadString(vob+16);
	}
	else { return ""; };
	printdebug(concatstrings("ZONEVOB.name:",zonevobname));
	//str = piratebay_PRB
	var int at; var int label;
	at = STR_Len(zonevobname);
	MEM_InitLabels(); 
	
	label = MEM_StackPos.position; 
	at = at - 1;
	if(STR_GetCharAt(zonevobname,at)==95)//'_'
	{
		var int zoneVobNameLength; zoneVobNameLength = STR_Len(zonevobname);    //recycled var..
		return Str_SubStr(zonevobname,at+1,zoneVobNameLength-at-1);	
	}
	else if (at>0)
	{
		MEM_StackPos.position = label;	
	};
	return "";
};


var int MusicSystem_MusicZoneAddress_Last;
var int MusicSystem_HeroStatus_Last;

// Exctract method, its nice to know theese things 
func void MusicSystem_SetNewTheme()
{
	var string filename;
	var int herostatus; herostatus = MEM_ReadInt(MUSIC_HeroStatus_Address);
		filename = MusicSystem_GetTheme();
		printdebug(concatstrings("MS:MusicSys_OldThemePrefix:",MusicSys_OldThemePrefix));
		printdebug(concatstrings("MS:MusicSys_NewThemePrefix:",filename));
		
		// Don't do nothing if new Theme is same theme as old one
		// and herostatus won't changed too
		if(Hlp_StrCmp(filename,MusicSys_OldThemePrefix) && herostatus == MusicSystem_HeroStatus_Last){return;}
		else { MusicSys_OldThemePrefix = filename; };
		
		// Default motif have night variation:
		// (I don't think so)
		if(Hlp_StrCmp(filename,"DEF"))
		{
			printdebug("it's DEF!!!");
			if(Wld_IsTime(20,00,5,00))
			{
				//Note: Looks like night theme will never happen ;)
				//filename = ConcatStrings(filename,"_NGT");		
			};
		};
		filename = ConcatStrings(filename,"_DAY");	
		printdebug(concatstrings("MS:FilenamePREFIX:",filename));		
		
		if(herostatus==0)//to std
		{
			filename = ConcatStrings(filename,"_STD.ogg");	
		}
		else//else to fgt
		{
			if(Hlp_StrCmp(filename,"PSI_DAY"))
			{//separated fight theme is only availble for psi motif
				printdebug(concatstrings("MS:Fight PSI!:",""));
				filename = ConcatStrings(filename,"_FGT.ogg");	
			}
			else if(Hlp_StrCmp(filename,"OGY_DAY"))
			{//huh, kidding (just forgot about OGY)
				printdebug(concatstrings("MS:Fight OGY!:",""));
				filename = ConcatStrings(filename,"_FGT.ogg");	
			}
			else
			{//theme is DEF or any else theme that will use DEF FGT theme:
				printdebug(concatstrings("MS:Picking Random DEF Fight-Theme:",filename));
				var int rnd; rnd = Hlp_Random(3);
				
				filename = "DEF_DAY_FGT.ogg";
				if(rnd==0)
				{
					filename = "DEF_DAY_FGT.ogg";
				}
				else if(rnd==1)
				{
					filename = "DEF2_DAY_FGT.ogg";			
				}
				else
				{
					filename = "DEF3_DAY_FGT.ogg";
				};
			};		
		};		
		//TODO: get volume level from zCMusicZone object maybe?
		MusicSystem_PlayMusic(FILENAME,mkf(1));		
		MusicSystem_HeroStatus_Last = herostatus;
		printdebug(concatstrings("MS:filename:",filename));
		
};

// Wiec ta funkcja jest wywoływana przez *loop* z opoznieniem 0.125
func void MusicSystem_Callback()
{
	var int musiczone; // Pointer to zCMusicZone object that hero is in
	var int herostatus; // Jakiś magiczny status odnosnie obecnego stanu bohatera: eksploracja / walka / zagr?
	var string filename;
	printdebug("MS:MusicSystem_Callback()");
	
	//First, handle the boss-fight motives:
	if(BOSSFIGHT_CURRENT==BOSSFIGHT_FGT1)
	{
		filename = MusicSystem_GetTheme();		
		MusicSys_OldThemePrefix = filename;	
		herostatus = 1;
		MusicSystem_MusicZoneAddress_Last = 0;
		MusicSystem_PlayMusic("BOSSFGT1_DAY_STD.ogg",mkf(1));
		return;
	};
	
	musiczone = MEM_ReadInt(MUSIC_Zone_Address);
	// Zmiana strefy muzycznej / wczytanie gry (zmiana adresu music zone)
	if(musiczone!=MusicSystem_MusicZoneAddress_Last)//change music: std->std or fgt->fgt
	{	// so new musiczone != last music zone
	
		printdebug("MS:musiczone != lastmusiczone");
		MusicSystem_SetNewTheme();
	}
	else
	{	// There is no changes in music zone, but we should keep eye
		// on herostatus -> so when he start's to fight we sould change Theme to it's fight variation
		
		printdebug("MS:musiczone == lastmusiczone");
		herostatus = MEM_ReadInt(MUSIC_HeroStatus_Address);
		if(herostatus!=MusicSystem_HeroStatus_Last)//change music std->fgt/fgt->std (same theme)
		{
			printdebug("MS:herostatus != lastHeroStatus");
			filename = MusicSystem_GetTheme();
			MusicSystem_SetNewTheme();			
			MusicSys_OldThemePrefix = filename;			
		}; 
		
	};
	// Ork: To powinno mnie oświecić codo problemów ze powrotem muzyki z fight -> standard
	printscreen_s_i_s_i("Current musicZone.ptr: ",musiczone,"; herostatus: ",herostatus
	,5,5,1);
		MusicSystem_MusicZoneAddress_Last = musiczone;
	
	//Tidy is needed evry 125ms now
	//if(MusicSys_TidyDelay)
	//{ 
	//	MusicSys_TidyDelay-=125;
	//	if(MusicSys_TidyDelay<=0)
	//	{
			MusicSystem_Tidy();
	//	};
	//};//timems - 125ms
	

	
	
};